# 파일 경로: .github/workflows/hello.yml
name: Hello Actions

on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello GitHub Actions!"
